### ISSUE TITLE
Me da error a la hora de ejecutar

### ISSUE THREAD

**Issue by mmm286** [tanrax/wallapop-alert#6]
Hola,
Estoy intentando ejecutarlo pero me da el siguiente error:

./wallapop_alert.py -k gameboy
Traceback (most recent call last):
  File "./wallapop_alert.py", line 3, in <module>
    import demiurge, sys, getopt, os, pickle, tempfile
  File "/usr/local/lib/python3.4/dist-packages/demiurge/__init__.py", line 7, in <module>
    from .demiurge import (
  File "/usr/local/lib/python3.4/dist-packages/demiurge/demiurge.py", line 5, in <module>
    import pyquery
  File "/usr/local/lib/python3.4/dist-packages/pyquery/__init__.py", line 7, in <module>
    from .pyquery import PyQuery  # NOQA
  File "/usr/local/lib/python3.4/dist-packages/pyquery/pyquery.py", line 10, in <module>
    from lxml import etree
ImportError: No module named 'lxml'

Me puedes ayudar? Gracias y saludos,

**Comment by tanrax** [comment]
Intenta con Python 3.6

No obstante tienes https://wallaviso.com/ :)

**Comment by svonjoi** [comment]
q ha pasado con wallaviso?

**Comment by tanrax** [comment]
Murió: https://programadorwebvalencia.com/wallaviso-por-que-no-funciono-un-servicio-de-avisos-para-wallapop/
